# -*- coding:utf-8 -*-

from unittest import TestCase
from decimal import Decimal
from datetime import datetime

from notacarioca.main import NotaCarioca

class TestNotaCarioca(TestCase):

    def setUp(self):
        self.certificate = "-----BEGIN CERTIFICATE-----\nMIIIZTCCBk2gAwIBAgIQSpCjaeQFsFdHY+I89G/nizANBgkqhkiG9w0BAQsFADB4\nMQswCQYDVQQGEwJCUjETMBEGA1UEChMKSUNQLUJyYXNpbDE2MDQGA1UECxMtU2Vj\ncmV0YXJpYSBkYSBSZWNlaXRhIEZlZGVyYWwgZG8gQnJhc2lsIC0gUkZCMRwwGgYD\nVQQDExNBQyBDZXJ0aXNpZ24gUkZCIEc0MB4XDTE1MDExNDAwMDAwMFoXDTE2MDEx\nMzIzNTk1OVowggEBMQswCQYDVQQGEwJCUjETMBEGA1UEChQKSUNQLUJyYXNpbDEL\nMAkGA1UECBMCUkoxFzAVBgNVBAcUDnJpbyBkZSBqYW5laXJvMTYwNAYDVQQLFC1T\nZWNyZXRhcmlhIGRhIFJlY2VpdGEgRmVkZXJhbCBkbyBCcmFzaWwgLSBSRkIxFjAU\nBgNVBAsUDVJGQiBlLUNOUEogQTExITAfBgNVBAsUGEF1dGVudGljYWRvIHBvciBB\nUiBJU0lHTjFEMEIGA1UEAxM7TVlGSU5BTkNFIENPTlNVTFRPUklBIEUgSU5GT1JN\nQVRJQ0EgTFREQSBFUFA6MTc3OTkzNzcwMDAxNTUwggEiMA0GCSqGSIb3DQEBAQUA\nA4IBDwAwggEKAoIBAQCoXB44g2jGoy35xUY4aLbqr0uEuL5Ai5BpBMLY3Xe7aJxo\n4+nMkpzAf53vKEPlUB/xb7Tiopb5CZjtsHtll8thWcvnhk8IW1MKKxjTwxp35Bbj\nc8YzhVEuQMsyMlOxZ/QbZ1aAhK/mZq377KVuFq8rtY/AQZHHlGghEw2lzitcATki\nSQamFLS/wPCx38rukWP1y+5YOYtbHqovIvRrOPQksEuRkdYTeNiQTpDLHepJVZkt\n3E9PWDq3RgXQhrzxt+rmL0mUxNuPjBDApxzCwN6kpngh+l7/B0RgEsOQsrb9fxPu\nwzf519nYnbkWvV948Ph+Lwqg63F29c1MT67ZKOUfAgMBAAGjggNeMIIDWjCBwwYD\nVR0RBIG7MIG4oD0GBWBMAQMEoDQEMjI1MDUxOTYwNTk2MjQ5NDk3MDAwMDAwMDAw\nMDAwMDAwMDAwMDA0Njk3ODY5OElGUFJKoCMGBWBMAQMCoBoEGEpBTkUgTUFSSUEg\nU09VU0EgTUFSVElOU6AZBgVgTAEDA6AQBA4xNzc5OTM3NzAwMDE1NaAXBgVgTAED\nB6AOBAwwMDAwMDAwMDAwMDCBHmFkbWluaXN0cmFjYW9AbXlmaW5hbmNlLmNvbS5i\ncjAJBgNVHRMEAjAAMB8GA1UdIwQYMBaAFC6R6tZt5bJZgtw4hSl2NBZWPNA+MA4G\nA1UdDwEB/wQEAwIF4DB/BgNVHSAEeDB2MHQGBmBMAQIBDDBqMGgGCCsGAQUFBwIB\nFlxodHRwOi8vaWNwLWJyYXNpbC5jZXJ0aXNpZ24uY29tLmJyL3JlcG9zaXRvcmlv\nL2RwYy9BQ19DZXJ0aXNpZ25fUkZCL0RQQ19BQ19DZXJ0aXNpZ25fUkZCLnBkZjCC\nARYGA1UdHwSCAQ0wggEJMFegVaBThlFodHRwOi8vaWNwLWJyYXNpbC5jZXJ0aXNp\nZ24uY29tLmJyL3JlcG9zaXRvcmlvL2xjci9BQ0NlcnRpc2lnblJGQkc0L0xhdGVz\ndENSTC5jcmwwVqBUoFKGUGh0dHA6Ly9pY3AtYnJhc2lsLm91dHJhbGNyLmNvbS5i\nci9yZXBvc2l0b3Jpby9sY3IvQUNDZXJ0aXNpZ25SRkJHNC9MYXRlc3RDUkwuY3Js\nMFagVKBShlBodHRwOi8vcmVwb3NpdG9yaW8uaWNwYnJhc2lsLmdvdi5ici9sY3Iv\nQ2VydGlzaWduL0FDQ2VydGlzaWduUkZCRzQvTGF0ZXN0Q1JMLmNybDAdBgNVHSUE\nFjAUBggrBgEFBQcDAgYIKwYBBQUHAwQwgZsGCCsGAQUFBwEBBIGOMIGLMF8GCCsG\nAQUFBzAChlNodHRwOi8vaWNwLWJyYXNpbC5jZXJ0aXNpZ24uY29tLmJyL3JlcG9z\naXRvcmlvL2NlcnRpZmljYWRvcy9BQ19DZXJ0aXNpZ25fUkZCX0c0LnA3YzAoBggr\nBgEFBQcwAYYcaHR0cDovL29jc3AuY2VydGlzaWduLmNvbS5icjANBgkqhkiG9w0B\nAQsFAAOCAgEAWGssO/MxSlV1TW+iRb0dTLooB/P8zqOOlSkyoQdHrtE7+42xXmmN\nUeU7J62QttDCQrzP81d63hfMLRNa2IjQmxdFpoeQjIdh0OP0ekfnq1mhLqQI6Bn1\n1sH3KMojhNAmST/EByGfcwjyDyyPYfjFeQcA3FuVmzEIGLfQcrMEX+DJXMgMUqn3\nsOdhTUbBFC/brP+F0k3H7rAPvkutwjJz/XnGYEDNovRHn0VSwjpKP7KRLjAwLAbV\nFfEnT3V1vNIa6AIulMnrXJhG00vhybYcBFAFcjStSwEqLIDiKr0BkMDqctGSJmwz\nCiaZAOY4dDl5AcGCnb1NZfoJLabLJQz7zyx0R8vUB2A+oQvLMsxHuuMvubihI+52\ncNpNYf/H6rSwwtQI2GzvtKAyr7cmcwg67begTh3BfBptFbwISRIU70wzKmKZWltV\nfaZbWwnXOaizbbl/O0vnGEgzXC2RBKjGtrJrXWL2rF5/AqCmqP4wWbTgTQdyW3hQ\nUJ3XT3Za/OMCvUOQ3F7IhmOQpmrUVGoqsUeZiMsKpIEPkD60RpZFei9k1LbssS4G\nccMIYu8FWOaIjre2BMB+rPoaLPcGe3c1+Krs22N57m5sMcKCTuuRGDHm1tQ4IZUc\nbHHwIe2XqTN/roj/x8gkgnZc0LaeErUqNimMZwWgb2dFid4MutfqF1Y=\n-----END CERTIFICATE-----\n"
        self.key = "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCoXB44g2jGoy35\nxUY4aLbqr0uEuL5Ai5BpBMLY3Xe7aJxo4+nMkpzAf53vKEPlUB/xb7Tiopb5CZjt\nsHtll8thWcvnhk8IW1MKKxjTwxp35Bbjc8YzhVEuQMsyMlOxZ/QbZ1aAhK/mZq37\n7KVuFq8rtY/AQZHHlGghEw2lzitcATkiSQamFLS/wPCx38rukWP1y+5YOYtbHqov\nIvRrOPQksEuRkdYTeNiQTpDLHepJVZkt3E9PWDq3RgXQhrzxt+rmL0mUxNuPjBDA\npxzCwN6kpngh+l7/B0RgEsOQsrb9fxPuwzf519nYnbkWvV948Ph+Lwqg63F29c1M\nT67ZKOUfAgMBAAECggEALuvlfEibdejakmb5qBT/Da8nM+ktFN4QtEQgbcJjcTa5\niL4kVeBykW+/u3yUV5+aF3bTiepYezXCilQKQAkrJImbO36CHkkdfpL+S15vzQQj\noOaOUaOROXvTZb0C+EmJje2h/RV91I+/Y5vTizgFQABM/P8JOv9Qeg9OWWx5Rx2X\nHCvhRm6zJYOraJ3PHjj1jLaldFgZ6YU43bfYOy2cCD2vVa+BEP9I97HCsoXNuklS\nvSUfD3Jj9opEGEav+N5xOKJbfkN2qanijIqZ1OzCE9mJYY6oZ62oPAv/6Z/GbVAE\nj++LKLGLVyGh3jHIMtvrCxrVR/gU9HsNXjVPDrJqyQKBgQDxfe1HhOvxbHlQaTvd\noEhqourMtxS1ati10eiTVW4oX95nqoYVR1YQLwgkdzBjxyP1qKY4xq2cwuWmpJKO\nosauBEOohxYz85/xjZv1mGfSohOwqFh7MOQc/RP4TZx8v/hcDuY8Iy9GQ+vGPrRO\nuqBgmzHv8ejQrdn9M4N+W92r8wKBgQCyeXEg6fcN+Isn2vaKT6vqSg+JG9vvfqw1\nfy21qBeWBSDyHAOgnCP9FHjOA7jSfMTgDGHif7tm/Dx0RaJL8bPx89pGkn9PZDAD\nBYD+RhO12I8lVpBpn8Wc9L48yCwFf1MV5MRtNamLCSOv/Za/E/M/ufrey+uAwFzV\nq+ms0v6JJQKBgQDOqMkp7yJK1F1s5uGIY+YU+56b2gEqz2jtD9lMXEuM2Z3mcROV\nmhqYducs7aLHgF/RlqXI6J0iDdehqCyTS9FikdukmRXzF4XEnT7eCbKvmmvnPema\nYtiTxjAUybYlO9M6VLXKuQF3zCA04uxCg4tDoQw3HnnyOxTVjgP1WoB06QKBgAMV\nLesPn4DSRjUOBywkbCfD17jajlX4rijOZY+5s46X0BXefgGMMOLyM5P7ZHneRdhI\n3nf3FNmWicTIXyFIr38CY0bMyP4qENo8ghniQ/zkHLTcZeotJFCtuYt7Oadup5S9\nOtdYEfGg2sjzbGMoiQ8Uu0yV4R98Mx5Ntd+SVWsxAoGBAMLTocTUjDiFfCKe5DWa\nnAAemiSQ2xF28HNDASWO9wuTD0HiKrFK5XLiXRRI+0P+Jqy3wd4cANDk8+FAhEFC\n6BhVZ15MUpgkuiQca9doc5z5/qUxMiaH6hG0f4HWRpu8tG6FNseFt3alHmAavvhf\n744aF+tZ7FYMbhPTJtkOtDvU\n-----END PRIVATE KEY-----\n"
        self.rps = {
            'taker':None,
            'service':{
                'city':u'Rio de Janeiro',
                'city_code_siafi':None,
                'city_tax_code':u'010501',
                'description':u'Consultoria em Inform\xe1tica',
                'values':{
                    'service_amount':Decimal('99.90'),
                    'ir_percentage':None,
                    'inss_amount':0.0,
                    'cofins_percentage':None,
                    'iss_amount':Decimal('4.99'),
                    'cnae_code':0.0,
                    'deduction_amount':0.0,
                    'inss_percentage':None,
                    'retained_iss_amount':0.0,
                    'unconditioned_discount':0.0,
                    'liquid_amount':Decimal('99.90'),
                    'pis_percentage':None,
                    'other_retentions_amount':0.0,
                    'aliquota':Decimal('5.00'),
                    'discount_conditioning':0.0,
                    'ir_amount':0.0,
                    'csll_percentage':None,
                    'pis_amount':0.0,
                    'calculation_base':Decimal('99.90'),
                    'csll_amount':0.0,
                    'retained_iss':2,
                    'cofins_amount':0.0
                },
                'service_item_list':u'0105',
                'city_code':3304557
            },
            'emitter':{
                'cnpj':u'17799377000155',
                'city_inscription':u'05725984',
                'national_simple':2,
                'cultural_promoter':2
            },
            'substitute_rps':None,
            u'id':237,
            'is_complete':True,
            'allow_incomplete':False,
            'batch':None,
            'status':u'created',
            'description':u'Aguardando o envio para a Sefaz.',
            'nfse_key':u'',
            'nfse_number':u'',
            'protocol':u'',
            'send_nfse_taker':False,
            'confirmation_display':False,
            'hash_nfse_viewed':u'',
            'taker_city_code_desc':u'',
            'is_api':False,
            'user':1,
            'nfse_mirror':None,
            'nfse_xml':None,
            'number':47,
            'serie':u'1',
            'rps_type':u'1',
            'emission_date':datetime(2015, 9, 28, 9, 51),
            'emission_date_nfse':None,
            'operation_nature':u'1',
            'rps_situation':u'1',
            'other_informations':u'',
            'competence':None,
            'special_regime':u'',
            'emitter_email':u'comercial@myfinance.com.br',
            'emitter_cnpj':u'17799377000155',
            'emitter_social_reason':u'Myfinance Consultoria e Inform\xe1tica Ltda ME',
            'emitter_fancy_name':u'Myfinance',
            'emitter_state_inscription':u'ISENTO',
            'emitter_city_inscription':u'05725984',
            'emitter_neighborhood':u'Centro',
            'emitter_street':u'Rua do Carmo',
            'emitter_number':u'43',
            'emitter_complement':u'8\xba andar',
            'emitter_zip_code':u'20011020',
            'emitter_phone':u'2135011000',
            'emitter_environment':u'sandbox',
            'emitter_national_simple_optant':False,
            'emitter_cultural_promoter':False,
            'service_values_city_code':3304557,
            'service_values_city_tax_code':u'010501',
            'service_values_service_item_code':u'0105',
            'service_values_cnae_code':u'',
            'service_values_service_amount':Decimal('99.90'),
            'service_values_discount_conditioning_amount':Decimal('0.00'),
            'service_values_discount_conditioning_percentage':None,
            'service_values_unconditioned_discount_amount':Decimal('0.00'),
            'service_values_unconditioned_discount_percentage':None,
            'service_values_deduction_amount':Decimal('0.00'),
            'service_values_deduction_percentage':None,
            'service_values_other_retentions_amount':Decimal('0.00'),
            'service_values_other_retentions_percentage':None,
            'service_values_calculation_base':Decimal('99.90'),
            'service_values_iss_amount':Decimal('4.99'),
            'service_values_iss_percentage':Decimal('5.00'),
            'service_values_pis_amount':Decimal('0.00'),
            'service_values_pis_percentage':None,
            'service_values_cofins_amount':Decimal('0.00'),
            'service_values_cofins_percentage':None,
            'service_values_inss_amount':Decimal('0.00'),
            'service_values_inss_percentage':None,
            'service_values_ir_amount':Decimal('0.00'),
            'service_values_ir_percentage':None,
            'service_values_csll_amount':Decimal('0.00'),
            'service_values_csll_percentage':None,
            'service_values_retained_iss':False,
            'service_values_retained_iss_amount':None,
            'service_values_retained_iss_percentage':None,
            'service_values_nfse_liquid_amount':Decimal('99.90'),
            'service_values_description':u'Consultoria em Inform\xe1tica',
            'service_values_city_tax_code_desc':u'',
            'service_values_city_code_desc':u'Rio de Janeiro',
            'service_values_cnae_code_desc':u'',
            'service_values_service_item_code_desc':u'',
            'has_taker':False,
            'taker_cpf':u'',
            'taker_cnpj':u'',
            'taker_city_inscription':u'',
            'taker_social_reason':u'',
            'taker_fancy_name':u'',
            'taker_state_inscription':u'',
            'taker_substitute_state_inscription':u'',
            'taker_special_situation':None,
            'taker_foreign_taker':False,
            'taker_phone':u'',
            'taker_email':u'',
            'taker_street':u'',
            'taker_number':u'',
            'taker_complement':u'',
            'taker_neighborhood':u'',
            'taker_city_code':None,
            'taker_state':None,
            'taker_zip_code':u'',
            'taker_street_type':None,
            'taker_neighborhood_type':None,
            'taker_city':u'',
            'taker_reference_point':u'',
            'taker_country':u'BR',
            'taker_country_code':u'01058',
            'taker_country_abbreviation':u'BR'
        }

    def test_send(self):
        nota = NotaCarioca(key=self.key, certificate=self.certificate, city_code=3304557, env="sandbox", **self.rps)
        response = nota.send()
